/*
 * Licensed to the OpenAirInterface (OAI) Software Alliance under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The OpenAirInterface Software Alliance licenses this file to You under
 * the OAI Public License, Version 1.1  (the "License"); you may not use this file
 * except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.openairinterface.org/?page_id=698
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *-------------------------------------------------------------------------------
 * For more information about the OpenAirInterface (OAI) Software Alliance:
 *      contact@openairinterface.org
 */

/* Header file generated by fdesign on Thu Aug 28 12:13:51 2014 */

// executables/sockVars.h


#ifndef SOCKVARS_H
#define SOCKVARS_H
#include <netinet/in.h>
#include <sys/socket.h>
#include <arpa/inet.h>

extern int sockfd;
extern struct sockaddr_in server_addr;
/* legacy names also exported by sockVars.c */
extern int prach_sockfd;
extern struct sockaddr_in prach_server_addr;
/* initialize/close helper for PRACH UDP (defined in sockVars.c) */
int prach_socket_init(const char *ip, int port);
void prach_socket_close(void);
#endif

